/*
  Practica 2 - Jenkinsfile  Pipelines CI/CD en Jenkins con Docker y Groovy 
*/

// =========================
// Ejercicio 4 (Groovy): función reutilizable
// =========================
def runInDocker(String image, Closure body) {
  // TODO (E4): Ejecuta `body()` dentro del contenedor indicado usando Docker Pipeline:
  docker.image(image).inside { body() }
}


pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {
    stage('Info') {
      steps {
        // TODO (E1): imprime JOB_NAME y BUILD_NUMBER
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }


    // =========================
    // Ejercicio 3 (preparación): construir imagen CI con make
    // =========================
    stage('CI - Build tools image') {
      steps {
        script {
          // TODO (E3): Construye una imagen de CI desde devops/ci.Dockerfile.
          env.CI_IMAGE_NAME = "python-ci-tools:${env.BUILD_NUMBER}"
          docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
        }
      }
    }

    // =========================
    // Ejercicio 3 (separar CI): stage Lint
    // =========================
    stage('CI - Lint') {
      steps {
        script {
          // TODO (E3/E4): Ejecuta lint en contenedor Python.
          runInDocker(env.CI_IMAGE_NAME) {
            sh 'pip install -r requirements.txt flake8 mypy'
            sh 'make lint'
          }
        }
      }
    }


    // =========================
    // Ejercicio 2 (Docker como agente) + Ejercicio 4 (refactor con runInDocker)
    // =========================
    stage('Test') {
        steps {
        script {
          // TODO (E2/E4): Ejecuta los tests unitarios dentro de la imagen CI construida.
          runInDocker(env.CI_IMAGE_NAME) {
            sh 'python --version'
            sh 'pip install -r requirements.txt'
            sh 'pytest -q'
          }
        }
      }
    }

   
  }
}
